name = "after-rust"
description = "A robust, elegant rust theme"
license = "MIT"
homepage = "https://github.com/vms20591/after-rust"
min_version = "0.11.0"

[extra]


[author]
name = "vms20591"
homepage = "https://github.com/vms20591/after-rust"

[original]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"
repo = "https://github.com/getzola/after-dark
